In [1]:
import numpy as np
import plb_ml_lib as pml

In [2]:
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
y = np.dot(X, np.array([1, 2])) + 3
print(y.shape)

(4,)


In [13]:
reg = pml.LinearRgressionNp(solver="gd")

In [14]:
reg.fit(X, y)

In [15]:
reg.predict(np.array([[3, 5]]))

array([[16.00000037]])

In [16]:
reg.coef_

array([[1.00000038],
       [1.99999995]])

In [17]:
reg.intercept_

array([2.9999995])